export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    logout: '/auth/logout',
    passwordResetConfirm: '/auth/password-reset/confirm',
    passwordResetRequest: '/auth/password-reset/request',
    refresh: '/auth/refresh',
    register: '/auth/register',
  },
  dashboard: {
    summary: '/dashboard/summary',
  },
  exports: {
    account: '/exports/account',
  },
  vehicles: {
    list: '/vehicles',
    create: '/vehicles',
    detail: (vehicleId: string) => `/vehicles/${vehicleId}`,
  },
  vehicleCatalog: {
    makes: '/vehicle-catalog/makes',
    models: '/vehicle-catalog/models',
    variants: '/vehicle-catalog/variants',
    importRuns: '/vehicle-catalog/import-runs',
    importRunDetail: (runId: string) => `/vehicle-catalog/import-runs/${runId}`,
    archiveMissingImportRun: (runId: string) => `/vehicle-catalog/import-runs/${runId}/archive-missing`,
    publishImportRun: (runId: string) => `/vehicle-catalog/import-runs/${runId}/publish`,
  },
  maintenance: {
    all: '/maintenance-records',
    list: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records`,
    create: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records`,
    detail: (recordId: string) => `/maintenance-records/${recordId}`,
    update: (recordId: string) => `/maintenance-records/${recordId}`,
    delete: (recordId: string) => `/maintenance-records/${recordId}`,
  },
  attachments: {
    byRecord: (recordId: string) => `/maintenance-records/${recordId}/attachments`,
    upload: (recordId: string) => `/maintenance-records/${recordId}/attachments`,
    reconcile: '/attachments/reconciliation',
    detail: (attachmentId: string) => `/attachments/${attachmentId}`,
    file: (attachmentId: string) => `/attachments/${attachmentId}/file`,
    delete: (attachmentId: string) => `/attachments/${attachmentId}`,
  },
  reminders: {
    list: '/reminders',
    byVehicle: (vehicleId: string) => `/vehicles/${vehicleId}/reminders`,
    detail: (reminderId: string) => `/reminders/${reminderId}`,
    create: (vehicleId: string) => `/vehicles/${vehicleId}/reminders`,
    update: (reminderId: string) => `/reminders/${reminderId}`,
    delete: (reminderId: string) => `/reminders/${reminderId}`,
    complete: (reminderId: string) => `/reminders/${reminderId}/complete`,
  },
} as const;
