export const endpoints = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
    logout: '/auth/logout',
    passwordResetConfirm: '/auth/password-reset/confirm',
    passwordResetRequest: '/auth/password-reset/request',
    refresh: '/auth/refresh',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
  },
  dashboard: {
    summary: '/dashboard/summary',
  },
  exports: {
    account: '/exports/account',
  },
  vehicles: {
    list: '/vehicles',
    create: '/vehicles',
    detail: (vehicleId: string) => `/vehicles/${vehicleId}`,
    insights: (vehicleId: string) => `/vehicles/${vehicleId}/insights`,
    forecast: (vehicleId: string) => `/vehicles/${vehicleId}/forecast`,
    serviceHistoryPdf: (vehicleId: string) => `/vehicles/${vehicleId}/service-history.pdf`,
    resaleReportPdf: (vehicleId: string, askingPrice?: number) =>
      askingPrice != null && askingPrice >= 0
        ? `/vehicles/${vehicleId}/resale-report.pdf?askingPrice=${askingPrice}`
        : `/vehicles/${vehicleId}/resale-report.pdf`,
  },
  vehicleCatalog: {
    makes: '/vehicle-catalog/makes',
    models: '/vehicle-catalog/models',
    variants: '/vehicle-catalog/variants',
    importRuns: '/vehicle-catalog/import-runs',
    importRunDetail: (runId: string) => `/vehicle-catalog/import-runs/${runId}`,
    archiveMissingImportRun: (runId: string) =>
      `/vehicle-catalog/import-runs/${runId}/archive-missing`,
    reviewOffering: (offeringId: string) => `/vehicle-catalog/offerings/${offeringId}/review`,
    publishImportRun: (runId: string) => `/vehicle-catalog/import-runs/${runId}/publish`,
    specs: '/vehicle-catalog/specs',
  },
  maintenance: {
    all: '/maintenance-records',
    list: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records`,
    create: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records`,
    bulk: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records/bulk`,
    createDraft: (vehicleId: string) => `/vehicles/${vehicleId}/maintenance-records/drafts`,
    detail: (recordId: string) => `/maintenance-records/${recordId}`,
    update: (recordId: string) => `/maintenance-records/${recordId}`,
    delete: (recordId: string) => `/maintenance-records/${recordId}`,
  },
  attachments: {
    extractionStatus: '/attachments/extraction/status',
    byRecord: (recordId: string) => `/maintenance-records/${recordId}/attachments`,
    upload: (recordId: string) => `/maintenance-records/${recordId}/attachments`,
    reconcile: '/attachments/reconciliation',
    detail: (attachmentId: string) => `/attachments/${attachmentId}`,
    extract: (attachmentId: string) => `/attachments/${attachmentId}/extract`,
    extractBatch: (recordId: string) => `/maintenance-records/${recordId}/attachments/extract`,
    applyExtraction: (attachmentId: string) => `/attachments/${attachmentId}/apply`,
    file: (attachmentId: string) => `/attachments/${attachmentId}/file`,
    delete: (attachmentId: string) => `/attachments/${attachmentId}`,
  },
  reminders: {
    list: '/reminders',
    byVehicle: (vehicleId: string) => `/vehicles/${vehicleId}/reminders`,
    detail: (reminderId: string) => `/reminders/${reminderId}`,
    create: (vehicleId: string) => `/vehicles/${vehicleId}/reminders`,
    update: (reminderId: string) => `/reminders/${reminderId}`,
    delete: (reminderId: string) => `/reminders/${reminderId}`,
    complete: (reminderId: string) => `/reminders/${reminderId}/complete`,
    scheduleSuggestions: (vehicleId: string) =>
      `/vehicles/${vehicleId}/service-schedule/suggestions`,
    applySchedule: (vehicleId: string) => `/vehicles/${vehicleId}/service-schedule/apply`,
  },
  fuelLogs: {
    byVehicle: (vehicleId: string) => `/fuel-logs/vehicle/${vehicleId}`,
    create: (vehicleId: string) => `/fuel-logs/vehicle/${vehicleId}`,
    bulk: (vehicleId: string) => `/fuel-logs/vehicle/${vehicleId}/bulk`,
    scan: () => `/fuel-logs/scan`,
    scanStatus: () => `/fuel-logs/scan/status`,
    detail: (id: string) => `/fuel-logs/${id}`,
    update: (id: string) => `/fuel-logs/${id}`,
    delete: (id: string) => `/fuel-logs/${id}`,
  },
  vehicleLoans: {
    list: '/vehicle-loans',
    byVehicle: (vehicleId: string) => `/vehicle-loans/vehicle/${vehicleId}`,
    create: (vehicleId: string) => `/vehicle-loans/vehicle/${vehicleId}`,
    detail: (id: string) => `/vehicle-loans/${id}`,
    update: (id: string) => `/vehicle-loans/${id}`,
    delete: (id: string) => `/vehicle-loans/${id}`,
    schedule: (id: string) => `/vehicle-loans/${id}/schedule`,
    addPrepayment: (id: string) => `/vehicle-loans/${id}/prepayments`,
    deletePrepayment: (id: string, prepaymentId: string) =>
      `/vehicle-loans/${id}/prepayments/${prepaymentId}`,
    foreclose: (id: string) => `/vehicle-loans/${id}/foreclose`,
    attachments: (id: string) => `/vehicle-loans/${id}/attachments`,
    uploadAttachments: (id: string) => `/vehicle-loans/${id}/attachments`,
    scan: () => `/vehicle-loans/scan`,
    scanStatus: () => `/vehicle-loans/scan/status`,
  },
  analytics: {
    costSplit: '/analytics/cost-split',
    costTrend: '/analytics/cost-trend',
    tco: (vehicleId: string) => `/analytics/tco/${vehicleId}`,
  },
  vehicleDocuments: {
    scan: (vehicleId: string) => `/vehicles/${vehicleId}/documents/scan`,
    scanStatus: (vehicleId: string) => `/vehicles/${vehicleId}/documents/scan/status`,
  },
  audit: {
    me: '/audit/me',
    byVehicle: (vehicleId: string) => `/vehicles/${vehicleId}/audit`,
  },
  admin: {
    users: '/admin/users',
    forceLogout: (userId: string) => `/admin/users/${userId}/force-logout`,
  },
  notifications: {
    list: () => '/notifications',
    unreadCount: () => '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: () => '/notifications/read-all',
    delete: (id: string) => `/notifications/${id}`,
  },
} as const;
