export type {
  DashboardAttentionCounts,
  DashboardAttentionItem,
  DashboardAttentionKind,
  DashboardDataGap,
  DashboardDocumentState,
  DashboardLoanSummary,
  DashboardMaintenanceSummary,
  DashboardReminderCounts,
  DashboardSummary,
  DashboardUrgency,
  DashboardVehicleDataHealth,
  DashboardVehicleDocumentStatus,
  DashboardVehicleHealth,
  DashboardVehicleLastService,
  DashboardVehicleNextDue,
  DashboardVehicleStatus,
} from '@vehicle-vault/shared';
