export enum MaintenanceCategory {
  PeriodicService = 'periodic_service',
  EngineOil = 'engine_oil',
  OilFilter = 'oil_filter',
  AirFilter = 'air_filter',
  BrakePads = 'brake_pads',
  TyreRotation = 'tyre_rotation',
  WheelAlignment = 'wheel_alignment',
  Battery = 'battery',
  Coolant = 'coolant',
  Clutch = 'clutch',
  ChainService = 'chain_service',
  TyreReplacement = 'tyre_replacement',
  Puncture = 'puncture',
  Insurance = 'insurance',
  Puc = 'puc',
  Other = 'other',
}
